//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class KDMSEntities : DbContext
    {
        public KDMSEntities()
            : base("name=KDMSEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<RestaurantMenu> RestaurantMenu { get; set; }
        public virtual DbSet<RestaurantDPMenu> RestaurantDPMenu { get; set; }
        public virtual DbSet<Sys_Menu> Sys_Menu { get; set; }
        public virtual DbSet<Sys_Resources> Sys_Resources { get; set; }
        public virtual DbSet<Sys_RoleResources> Sys_RoleResources { get; set; }
        public virtual DbSet<Sys_Roles> Sys_Roles { get; set; }
        public virtual DbSet<Sys_UserRole> Sys_UserRole { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
        public virtual DbSet<Base_KeyValue> Base_KeyValue { get; set; }
        public virtual DbSet<RestaurantEnvInfo> RestaurantEnvInfo { get; set; }
        public virtual DbSet<V_RestaurantEnvInfoKv> V_RestaurantEnvInfoKv { get; set; }
        public virtual DbSet<User_Event> User_Event { get; set; }
        public virtual DbSet<User_Work> User_Work { get; set; }

    }
}
