//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RestaurantEnvInfo
    {
        public System.Guid RestaurantId { get; set; }
        [Required(ErrorMessage = "请选择有无分店")]
        public Nullable<int> 有无分店 { get; set; }

        [Required(ErrorMessage = "请选择是否需要走楼梯")]
        public Nullable<int> 是否需要走楼梯_无电梯_ { get; set; }

        [Required(ErrorMessage = "请选择候位区")]
        public Nullable<int> 候位区 { get; set; }

        [Required(ErrorMessage = "请选择衣帽间")]
        public Nullable<int> 衣帽间 { get; set; }

        [Required(ErrorMessage = "请选择园景")]
        public Nullable<int> 园景_饭店区域内的花园_ { get; set; }

        [Required(ErrorMessage = "请选择背景音乐")]
        public Nullable<int> 背景音乐 { get; set; }

        [Required(ErrorMessage = "请选择空气清新度")]
        public Nullable<int> 空气清新度 { get; set; }

        [Required(ErrorMessage = "请选择服务人员形象")]
        public Nullable<int> 服务人员形象 { get; set; }

        [Required(ErrorMessage = "请选择邻桌动线有无干扰")]
        public Nullable<int> 邻桌动线有无干扰 { get; set; }

        [Required(ErrorMessage = "请选择传菜有无干扰")]
        public Nullable<int> 传菜有无干扰 { get; set; }

        [Required(ErrorMessage = "请输入空间感")]
        public string 空间感_高度_ { get; set; }

        [Required(ErrorMessage = "请选择照明")]
        public Nullable<int> 照明 { get; set; }

        [Required(ErrorMessage = "请选择采光")]
        public Nullable<int> 采光 { get; set; }

        [Required(ErrorMessage = "请选择软装品质")]
        public Nullable<int> 软装品质 { get; set; }

        [Required(ErrorMessage = "请选择硬装质感")]
        public Nullable<int> 硬装质感 { get; set; }

        [Required(ErrorMessage = "请选择地域特征")]
        public Nullable<int> 地域特征 { get; set; }

        [Required(ErrorMessage = "请选择文化艺术")]
        public Nullable<int> 文化艺术 { get; set; }

        [Required(ErrorMessage = "请选择餐具档次")]
        public Nullable<int> 餐具档次 { get; set; }

        [Required(ErrorMessage = "请选择餐具特色")]
        public Nullable<int> 餐具特色 { get; set; }

        [Required(ErrorMessage = "请选择菜单呈现")]
        public Nullable<int> 菜单呈现 { get; set; }

        [Required(ErrorMessage = "请选择桌子舒适度")]
        public Nullable<int> 桌子舒适度 { get; set; }

        [Required(ErrorMessage = "请选择椅子舒适度")]
        public Nullable<int> 椅子舒适度 { get; set; }

        [Required(ErrorMessage = "请选择移动拼桌")]
        public Nullable<int> 移动拼桌 { get; set; }

        [Required(ErrorMessage = "请选择衣服椅套")]
        public Nullable<int> 衣服椅套 { get; set; }

        [Required(ErrorMessage = "请选择御冷披肩")]
        public Nullable<int> 御冷披肩 { get; set; }

        [Required(ErrorMessage = "请选择舞台")]
        public Nullable<int> 舞台 { get; set; }

        [Required(ErrorMessage = "请选择吧台")]
        public Nullable<int> 吧台 { get; set; }

        [Required(ErrorMessage = "请选择演奏曲")]
        public Nullable<int> 演奏曲 { get; set; }

        [Required(ErrorMessage = "请选择播放区")]
        public Nullable<int> 播放区 { get; set; }

        [Required(ErrorMessage = "请选择露台")]
        public Nullable<int> 露台 { get; set; }

        [Required(ErrorMessage = "请选择露台景观")]
        public Nullable<int> 露台景观 { get; set; }

        [Required(ErrorMessage = "请选择儿童娱乐区")]
        public Nullable<int> 儿童娱乐区 { get; set; }

        [Required(ErrorMessage = "请选择厨房")]
        public Nullable<int> 厨房 { get; set; }

        [Required(ErrorMessage = "请选择包房")]
        public string 包房 { get; set; }

        [Required(ErrorMessage = "请选择包房卫生间")]
        public Nullable<int> 包房卫生间 { get; set; }

        [Required(ErrorMessage = "请选择卫生间距离")]
        public Nullable<int> 卫生间距离 { get; set; }

        [Required(ErrorMessage = "请选择卫生间")]
        public Nullable<int> 卫生间室内 { get; set; }

        [Required(ErrorMessage = "请选择卫生间洗手台")]
        public Nullable<int> 卫生间洗手台 { get; set; }

        [Required(ErrorMessage = "请选择卫生间坐厕间")]
        public Nullable<int> 卫生间坐厕间 { get; set; }

        [Required(ErrorMessage = "请选择儿童椅")]
        public Nullable<int> 儿童椅 { get; set; }

        [Required(ErrorMessage = "请选择儿童餐具")]
        public Nullable<int> 儿童餐具 { get; set; }

        [Required(ErrorMessage = "请选择可带宠物")]
        public Nullable<int> 可带宠物 { get; set; }

        [Required(ErrorMessage = "请选择免费WIFI")]
        public Nullable<int> 免费WIFI { get; set; }

        [Required(ErrorMessage = "请输入停车地点")]
        public string 停车_推荐地_ { get; set; }

        [Required(ErrorMessage = "请选择停车福利")]
        public Nullable<int> 停车福利 { get; set; }

        [Required(ErrorMessage = "请选择娱乐演艺")]
        public Nullable<int> 娱乐演艺 { get; set; }

        [Required(ErrorMessage = "请选择厨师表演")]
        public Nullable<int> 厨师表演 { get; set; }

        [Required(ErrorMessage = "请输入招牌菜")]
        public string 招牌菜 { get; set; }

        [Required(ErrorMessage = "请输入人气菜")]
        public string 人气菜 { get; set; }

        public string 新菜 { get; set; }

        [Required(ErrorMessage = "请选择有无隐藏菜单")]
        public Nullable<int> 有无隐藏菜单 { get; set; }

        [Required(ErrorMessage = "请选择能否接受预订")]
        public Nullable<int> 能否接受预订 { get; set; }
        [Required(ErrorMessage = "请输入最大单桌人数")]
        public string 最大单桌人数 { get; set; }
        [Required(ErrorMessage = "请输入接待桌数")]
        public string 接待桌数 { get; set; }
        public string 店内面积 { get; set; }


    }
}
