//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantDPMenu
    {
        public Nullable<System.Guid> Id { get; set; }
        public Nullable<System.Guid> RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string DPId { get; set; }
        public string DPDishId { get; set; }
        public Nullable<int> DPRecommand { get; set; }
        public string DPImgSrc { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
    }
}
