//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public System.Guid Id { get; set; }
        public string DPId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> DPMenuCount { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<bool> VisibleInApp { get; set; }
        public Nullable<int> EnvImgCount { get; set; }
        public Nullable<int> MenuImgCount { get; set; }
        public Nullable<int> MenuCount { get; set; }
        public Nullable<int> MeanPrice { get; set; }
        public Nullable<System.Guid> RestaurantEnvInfoId { get; set; }
        public string Creator { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
