//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Collections.Generic;
    public class Menus
    {
        public List<RestaurantMenu> Menu { get; set; }

    }
    public partial class RestaurantMenu
    {
        public Guid RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string DPId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public decimal? Price { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
        public DateTime? created { get; set; }
        public DateTime? modified { get; set; }
        public Guid? Id { get; set; }
        public string DPDishId { get; set; }
        public int? DPRecommand { get; set; }
        public string DPImgSrc { get; set; }

        public string Creator { get; set; }

        public int? UserId { get; set; }
    }
}
