//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Resources
    {
        public int ResId { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string ResourcesCode { get; set; }
        public string ResourcesName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Url { get; set; }
    }
}
