//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Collections.Generic;

    public partial class Sys_Users
    {
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EnglishName { get; set; }
        public string ContactTel { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }

        //确认密码
        public string NewPassword { get; set; }
        //确认新密码
        public string NewsPassword { get; set; }
    }
}
