//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RestaurantEnvInfoKv
    {
        public System.Guid RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string DPId { get; set; }
        public Nullable<int> MeanPrice { get; set; }
        public string RestaurantAddress { get; set; }
        public Nullable<int> 有无分店 { get; set; }
        public string 有无分店_desc { get; set; }
        public Nullable<int> 是否需要走楼梯_无电梯_ { get; set; }
        public string 是否需要走楼梯_无电梯__desc { get; set; }
        public Nullable<int> 候位区 { get; set; }
        public string 候位区_desc { get; set; }
        public Nullable<int> 衣帽间 { get; set; }
        public string 衣帽间_desc { get; set; }
        public Nullable<int> 园景_饭店区域内的花园_ { get; set; }
        public string 园景_饭店区域内的花园__desc { get; set; }
        public Nullable<int> 背景音乐 { get; set; }
        public string 背景音乐_desc { get; set; }
        public Nullable<int> 空气清新度 { get; set; }
        public string 空气清新度_desc { get; set; }
        public Nullable<int> 服务人员形象 { get; set; }
        public string 服务人员形象_desc { get; set; }
        public Nullable<int> 邻桌动线有无干扰 { get; set; }
        public string 邻桌动线有无干扰_desc { get; set; }
        public Nullable<int> 传菜有无干扰 { get; set; }
        public string 传菜有无干扰_desc { get; set; }
        public string 空间感_高度_ { get; set; }
        public Nullable<int> 照明 { get; set; }
        public string 照明_desc { get; set; }
        public Nullable<int> 采光 { get; set; }
        public string 采光_desc { get; set; }
        public Nullable<int> 软装品质 { get; set; }
        public string 软装品质_desc { get; set; }
        public Nullable<int> 硬装质感 { get; set; }
        public string 硬装质感_desc { get; set; }
        public Nullable<int> 地域特征 { get; set; }
        public string 地域特征_desc { get; set; }
        public Nullable<int> 文化艺术 { get; set; }
        public string 文化艺术_desc { get; set; }
        public Nullable<int> 餐具档次 { get; set; }
        public string 餐具档次_desc { get; set; }
        public Nullable<int> 餐具特色 { get; set; }
        public string 餐具特色_desc { get; set; }
        public Nullable<int> 菜单呈现 { get; set; }
        public string 菜单呈现_desc { get; set; }
        public Nullable<int> 桌子舒适度 { get; set; }
        public string 桌子舒适度_desc { get; set; }
        public Nullable<int> 椅子舒适度 { get; set; }
        public string 椅子舒适度_desc { get; set; }
        public Nullable<int> 移动拼桌 { get; set; }
        public string 移动拼桌_desc { get; set; }
        public Nullable<int> 衣服椅套 { get; set; }
        public string 衣服椅套_desc { get; set; }
        public Nullable<int> 御冷披肩 { get; set; }
        public string 御冷披肩_desc { get; set; }
        public Nullable<int> 舞台 { get; set; }
        public string 舞台_desc { get; set; }
        public Nullable<int> 吧台 { get; set; }
        public string 吧台_desc { get; set; }
        public Nullable<int> 演奏曲 { get; set; }
        public string 演奏曲_desc { get; set; }
        public Nullable<int> 播放区 { get; set; }
        public string 播放区_desc { get; set; }
        public Nullable<int> 露台 { get; set; }
        public string 露台_desc { get; set; }
        public Nullable<int> 露台景观 { get; set; }
        public string 露台景观_desc { get; set; }
        public Nullable<int> 儿童娱乐区 { get; set; }
        public string 儿童娱乐区_desc { get; set; }
        public Nullable<int> 厨房 { get; set; }
        public string 厨房_desc { get; set; }
        public string 包房 { get; set; }
        public string 包房_desc { get; set; }
        public Nullable<int> 包房卫生间 { get; set; }
        public string 包房卫生间_desc { get; set; }
        public Nullable<int> 卫生间距离 { get; set; }
        public string 卫生间距离_desc { get; set; }
        public Nullable<int> 卫生间室内 { get; set; }
        public string 卫生间室内_desc { get; set; }
        public Nullable<int> 卫生间洗手台 { get; set; }
        public string 卫生间洗手台_desc { get; set; }
        public Nullable<int> 卫生间坐厕间 { get; set; }
        public string 卫生间坐厕间_desc { get; set; }
        public Nullable<int> 儿童椅 { get; set; }
        public string 儿童椅_desc { get; set; }
        public Nullable<int> 儿童餐具 { get; set; }
        public string 儿童餐具_desc { get; set; }
        public Nullable<int> 可带宠物 { get; set; }
        public string 可带宠物_desc { get; set; }
        public Nullable<int> 免费WIFI { get; set; }
        public string 免费WIFI_desc { get; set; }
        public string 停车_推荐地_ { get; set; }
        public Nullable<int> 停车福利 { get; set; }
        public string 停车福利_desc { get; set; }
        public Nullable<int> 娱乐演艺 { get; set; }
        public string 娱乐演艺_desc { get; set; }
        public Nullable<int> 厨师表演 { get; set; }
        public string 厨师表演_desc { get; set; }
        public string 招牌菜 { get; set; }
        public string 人气菜 { get; set; }
        public string 新菜 { get; set; }
        public Nullable<int> 有无隐藏菜单 { get; set; }
        public string 有无隐藏菜单_desc { get; set; }
        public Nullable<int> 能否接受预订 { get; set; }
        public string 能否接受预订_desc { get; set; }
        public string 最大单桌人数 { get; set; }
        public string 接待桌数 { get; set; }
        public string 店内面积 { get; set; }

        public Nullable<System.DateTime> created { get; set; }
        public string Creator { get; set; }
    }
}
